/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const TenantId = IDL.Text;
export const Lead = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'tenantId' : TenantId,
  'phone' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : Time,
  'tenantId' : TenantId,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const AuditScore = IDL.Record({
  'lastUpdated' : Time,
  'tenantId' : TenantId,
  'score' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'tenantId' : TenantId,
});
export const FundabilityScore = IDL.Record({
  'lastUpdated' : Time,
  'tenantId' : TenantId,
  'score' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createLead' : IDL.Func([Lead], [], []),
  'createReview' : IDL.Func([Review], [], []),
  'deleteLead' : IDL.Func([TenantId, IDL.Text], [], []),
  'deleteReview' : IDL.Func([TenantId, IDL.Text], [], []),
  'getAuditScore' : IDL.Func([TenantId], [IDL.Opt(AuditScore)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFundabilityScore' : IDL.Func(
      [TenantId],
      [IDL.Opt(FundabilityScore)],
      ['query'],
    ),
  'getLeadById' : IDL.Func([TenantId, IDL.Text], [IDL.Opt(Lead)], ['query']),
  'getLeadsByTenantId' : IDL.Func([TenantId], [IDL.Vec(Lead)], ['query']),
  'getReviewById' : IDL.Func(
      [TenantId, IDL.Text],
      [IDL.Opt(Review)],
      ['query'],
    ),
  'getReviewsByTenantId' : IDL.Func([TenantId], [IDL.Vec(Review)], ['query']),
  'getTenantName' : IDL.Func([TenantId], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedDemoData' : IDL.Func([], [], []),
  'updateAuditScore' : IDL.Func([TenantId, IDL.Nat], [], []),
  'updateFundabilityScore' : IDL.Func([TenantId, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const TenantId = IDL.Text;
  const Lead = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'tenantId' : TenantId,
    'phone' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : Time,
    'tenantId' : TenantId,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const AuditScore = IDL.Record({
    'lastUpdated' : Time,
    'tenantId' : TenantId,
    'score' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'tenantId' : TenantId });
  const FundabilityScore = IDL.Record({
    'lastUpdated' : Time,
    'tenantId' : TenantId,
    'score' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createLead' : IDL.Func([Lead], [], []),
    'createReview' : IDL.Func([Review], [], []),
    'deleteLead' : IDL.Func([TenantId, IDL.Text], [], []),
    'deleteReview' : IDL.Func([TenantId, IDL.Text], [], []),
    'getAuditScore' : IDL.Func([TenantId], [IDL.Opt(AuditScore)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFundabilityScore' : IDL.Func(
        [TenantId],
        [IDL.Opt(FundabilityScore)],
        ['query'],
      ),
    'getLeadById' : IDL.Func([TenantId, IDL.Text], [IDL.Opt(Lead)], ['query']),
    'getLeadsByTenantId' : IDL.Func([TenantId], [IDL.Vec(Lead)], ['query']),
    'getReviewById' : IDL.Func(
        [TenantId, IDL.Text],
        [IDL.Opt(Review)],
        ['query'],
      ),
    'getReviewsByTenantId' : IDL.Func([TenantId], [IDL.Vec(Review)], ['query']),
    'getTenantName' : IDL.Func([TenantId], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedDemoData' : IDL.Func([], [], []),
    'updateAuditScore' : IDL.Func([TenantId, IDL.Nat], [], []),
    'updateFundabilityScore' : IDL.Func([TenantId, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };