/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditScore {
  'lastUpdated' : Time,
  'tenantId' : TenantId,
  'score' : bigint,
}
export interface FundabilityScore {
  'lastUpdated' : Time,
  'tenantId' : TenantId,
  'score' : bigint,
}
export interface Lead {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'tenantId' : TenantId,
  'phone' : string,
}
export interface Review {
  'id' : string,
  'createdAt' : Time,
  'tenantId' : TenantId,
  'comment' : string,
  'rating' : bigint,
}
export type TenantId = string;
export type Time = bigint;
export interface UserProfile { 'name' : string, 'tenantId' : TenantId }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createLead' : ActorMethod<[Lead], undefined>,
  'createReview' : ActorMethod<[Review], undefined>,
  'deleteLead' : ActorMethod<[TenantId, string], undefined>,
  'deleteReview' : ActorMethod<[TenantId, string], undefined>,
  'getAuditScore' : ActorMethod<[TenantId], [] | [AuditScore]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFundabilityScore' : ActorMethod<[TenantId], [] | [FundabilityScore]>,
  'getLeadById' : ActorMethod<[TenantId, string], [] | [Lead]>,
  'getLeadsByTenantId' : ActorMethod<[TenantId], Array<Lead>>,
  'getReviewById' : ActorMethod<[TenantId, string], [] | [Review]>,
  'getReviewsByTenantId' : ActorMethod<[TenantId], Array<Review>>,
  'getTenantName' : ActorMethod<[TenantId], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedDemoData' : ActorMethod<[], undefined>,
  'updateAuditScore' : ActorMethod<[TenantId, bigint], undefined>,
  'updateFundabilityScore' : ActorMethod<[TenantId, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];